Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -17,28 +17,14 @@ phases:
     commands:
       - set -eo pipefail
       - echo "checking if Rosetta needs to be installed"
-      - |
-        if [ "$(uname -m)" = "arm64" ]; then
-          /usr/sbin/softwareupdate --install-rosetta --agree-to-license
-        else
-          echo "Rosetta 2 can only be installed on Apple Silicon!"
-          exit 1
-        fi
+      - "if [ \"$(uname -m)\" = \"arm64\" ]; then /usr/sbin/softwareupdate --install-rosetta --agree-to-license; else echo \"Rosetta 2 can only be installed on Apple Silicon!\"; exit 1; fi"
   pre_build:
     commands:
       - echo "Current directory: $(pwd)"
       - echo "Listing directory contents:"
       - ls -la
-      - |
-        if [ ! -f "Gemfile" ]; then
-          echo "Error: Gemfile not found!"
-          exit 1
-        fi
-      - |
-        if [ ! -f "Podfile" ]; then
-          echo "Error: Podfile not found!"
-          exit 1
-        fi
+      - "if [ ! -f \"Gemfile\" ]; then echo \"Error: Gemfile not found!\"; exit 1; fi"
+      - "if [ ! -f \"Podfile\" ]; then echo \"Error: Podfile not found!\"; exit 1; fi"
       - echo "Check / Setup Shared DerivedData"
       - if [ ! -d "DerivedData" ]; then mkdir DerivedData; fi
       - echo "setup gems and pod install"
